config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "users/confirmation", to: 'availabilities#confirmation_page', as: :confirmation_page
  patch "users/:id/availabilities/confirmation", to: 'availabilities#confirmation', as: :confirmation
  resources :users, only: [ :index, :show]
  resources :chatrooms, only: [ :index, :show] do
    resources :messages, only: :create
  end
  resources :users do
    resources :reviews
  end
  get 'start_chat', to: 'chatrooms#start_chat', as: :start_chat
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user_one, class_name: "User"
  belongs_to :user_two, class_name: "User"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewer, class_name: "User"
  belongs_to :reviewee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # you have to use current_user.reviews_as_reviewer /reviewee
  has_many :reviews_as_reviewer, class_name: "Review", foreign_key: :reviewer_id
  has_many :reviews_as_reviewee, class_name: "Review", foreign_key: :reviewee_id
  has_many :availabilities
  has_many :messages
  has_many :chatrooms_one, class_name: "Chatroom", foreign_key: :user_one_id, dependent: :destroy
  has_many :chatrooms_two, class_name: "Chatroom", foreign_key: :user_two_id, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :confirmation_page], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController

  def edit
    @availability = Availability.find(params[:id])
  end

  def confirmation
    @availability = Availability.find(params[:id])
    @availabilities.update(av_params)
    raise
    redirect_to users_path(@user)
  end

  def confirmation_page
  end

  private

  def av_params
    params.require(:availabilities).permit(:offering, :looking, :hangout)
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
    def index
        @chatrooms = policy_scope(Chatroom).where(user_one: current_user).or(policy_scope(Chatroom).where(user_two: current_user))
    end

    def show
        @chatroom = Chatroom.find(params[:id])
        @message = Message.new
        authorize @chatroom
    end

    def start_chat
        @user = User.find(params[:user])
        condition_one = Chatroom.where(user_one: @user, user_two: current_user).empty?
        condition_two = Chatroom.where(user_one: current_user, user_two: @user).empty?
        if condition_one && condition_two
        @chatroom = Chatroom.create(user_one: @user, user_two: current_user)
        else
            if condition_one 
                @chatroom = Chatroom.where(user_one: current_user, user_two: @user).first  
            else
                @chatroom = Chatroom.where(user_one: @user, user_two: current_user).first 
            end
        end
        authorize @chatroom
        redirect_to chatroom_path(@chatroom)
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    def create
        @chatroom = Chatroom.find(params[:chatroom_id])
        @message = Message.new(message_params)
        @message.chatroom = @chatroom
        @message.user = current_user
        authorize @message
        if @message.save
          ChatroomChannel.broadcast_to(
            @chatroom,
            render_to_string(partial: "message", locals: { message: @message })
          )
          redirect_to chatroom_path(@chatroom, anchor: "message-#{@message.id}")
        else
          render "chatrooms/show"
        end
      end

      def message_params
        params.require(:message).permit(:content)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def confirmation
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_user
  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.reviewee_id = @user.id
    @review.reviewer_id = current_user.id
    authorize @review
    if @review.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  

  def index
    @users = policy_scope(User).order(created_at: :desc)
    if !params[:search].blank?
     @parameter = params[:search]
     @users = @users.where("city ILIKE :search", search: @parameter)
   end
 end


  def show 
   @user = User.find(params[:id])
    @reviews = Review.where(reviewee_id: @user.id)
    authorize @user

   @markers = 
    {
      lat: @user.latitude,
      lng: @user.longitude,
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/availabilities/confirmation_page.html.erb
  <div class="banner-two">
    <div class="container">
    <h1>Pop yourself up a cold beer and celebrate life !</h1>

     <div class="input-group-btn">
            <%= button_tag "Go Back To The Other Cool Kids", :class => 'btn btn-info glyphicon glyphicon-search'%>
          </div>
      </div>
</div>

app/views/chatrooms/index.html.erb
<div class="chatroom-container">
    <ul class='chatrooms-index-card-ul'>
        <%= link_to 'Back', :back %>
        <p class='chatrooms-header'>Messages From:</p>
        <% @chatrooms.each do |chatroom| %>
            <li class='chatrooms-index-card'>
                <%= link_to chatroom_path(chatroom), class: 'chat-link' do %>
                    <div class="chat-card">
                        <% if chatroom.user_one.id == current_user.id %>
                            <%= image_tag chatroom.user_two.profile_picture_url, alt: "", class: ""%>
                            <% else %>
                            <%= image_tag chatroom.user_one.profile_picture_url, alt: "", class: ""%>
                        <% end %>
                        <h3 class='chatrooms-index-card-name'><%= chatroom.user_one.id == current_user.id ? chatroom.user_two.name : chatroom.user_one.name %></h3>
                    </div>
                <% end %>
            </li>
        <% end %>
    </ul>
</div>

app/views/chatrooms/show.html.erb
<h1><%= @chatroom.name %></h1>

<div class="chat-container">
  <%= link_to 'Back', :back, class: 'go-back-link' %>

  <div class="chatroom-header">
    <div class="user-header <%= @chatroom.user_one_id == current_user.id ? 'user-left' : 'user-right' %>">
      <%= image_tag @chatroom.user_one.profile_picture_url, alt: "", class: ""%>
      <h3 class='chatroom-username'><%= @chatroom.user_one.name %></h3>
    </div>
    <div class="user-header <%= @chatroom.user_two_id == current_user.id ? 'user-left' : 'user-right' %>">
      <%= image_tag @chatroom.user_two.profile_picture_url, alt: "", class: ""%>   
      <h3 class='chatroom-username'><%= @chatroom.user_two.name %></h3>
    </div>
  </div>


  <div id="messages" data-chatroom-id="<%= @chatroom.id %>" data-current-user-id="<%= current_user.id %>">
    <% @chatroom.messages.each do |message| %>

        <% if message.user_id == current_user.id %>
          <%= render 'messages/message', message: message, css_class: 'sent-message' %>
        <% else %>
          <%= render 'messages/message', message: message, css_class: 'received-message' %>
        <% end %>
    
    <% end %>
  </div>
</div>

  <div class="message-form-container">
    <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
      <%= f.input :content, label: false, placeholder: "Your message" %>
      <%= f.button :submit, 'Send', class: 'btn primary-button'%>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quouch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>

  </head>
    <body>
      <%= render 'shared/navbar' if current_user && params[:action] != "home"%>
      <%= render 'shared/flashes' %>
     <%= yield %>

    </body>
</html>

app/views/messages/_message.html.erb
<div class="message-container <%= local_assigns[:css_class] %>" id="message-<%= message.id %>" data-sender-id="<%= message.user.id %>">
   <%= image_tag message.user.profile_picture_url, alt: "", class: "message-picture"%>
   <div class="username-time-container">
      <div class="time-date">
         <small ><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
         <p><%= message.content %></p>
      </div>
   </div>
</div>

app/views/pages/home.html.erb
<div class="bg-img">
  <%= content_for(:navbar_class, "navbar-home") %>

  <div class = "container homepagebox">
   <h1>Quouch</h1>
   <p>No more overnight stays with horny single men</p>
   <div class ="searchbar">
      <%= form_tag(users_path, :method => "get", class: 'navbar-form navbar-left' ) do %>
      <!-- <p>What's your next destination?</p> -->
      <!-- <p>No more overnight stays with horny single men</p> -->
        <input type="search" class="form-control" placeholder="Berlin" aria-label="Search" name="search">
        <button type="submit" class="btn primary-button w-100"><i class="fas fa-search"></i> Search</button>

        <p>Couchsurfing from a female & queer perspective </p>
      <% end %>
   </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-4">
      <%= simple_form_for([@user, @review]) do |f| %>
      <%= f.input :rating %>
      <%= f.input :content %>
      <%= f.submit "Create Review", class: 'btn primary-button'%>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h2>New Review</h2>

<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex">
        <%= link_to " Inbox", chatrooms_path, class: "nav-link", class: "fas"  %>
        <%= link_to " Sign Out", destroy_user_session_path, class: "nav-link", method: :delete, class: "fas" %>
</div>

 <!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%#= link_to "Messages", chatrooms_path, class: "nav-link", class: "fas fa-circle" %>

%>
      </li>
      <li class="nav-item dropdown">
        <%#= image_tag current_user.profile_picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%#= link_to "Messages", chatrooms_path, class: "dropdown-item" %>
          <%#= link_to "Sign-out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>
      </li>
    </ul>
  </div>
</div>


<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex">
  <%#= link_to "#", class: "navbar-brand" do %>
    <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <%# end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

 -->
 <!--  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%#= link_to "Messages", chatrooms_path, class: "nav-link", class: "fas fa-circle" %>

%>
      </li>
      <li class="nav-item dropdown">
        <%#= image_tag current_user.profile_picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%#= link_to "Messages", chatrooms_path, class: "dropdown-item" %>
          <%#= link_to "Sign-out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>
      </li>
    </ul>
  </div>
</div> -->

app/views/users/index.html.erb
<div class="container">
 <!--  <div class="alert alert-warning alert-dismissible fade show" role="alert">
  No more stays with horny men.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div> -->
  <div class="quouchers"><p>Quouchers in <%= params[:search].capitalize %></p></div>
      <div class="masonry">
      <% @users.each do |user| %>
           <%= link_to user_path(user), class: "grid-user" do  %>
        <div class="grid-item">
           <%= image_tag user.profile_picture_url, alt: "alttext", class: "grid-item-picture"%>
           <div class="grid-item-infos">
            <p class="grid-item-title"><%= user.name %></p>
            <p class="grid-item-bio"><%= truncate(user.bio, length: 50) %></p>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="top-card">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag @user.profile_picture_url %>
          </div>
          <div class="carousel-item">
            <div id="map"
                style="width: 400px; height: 345px;"
                  data-markers="<%= @markers.to_json %>"
                  data-mapbox-api-key="pk.eyJ1IjoiZHVzYW4tcCIsImEiOiJja29lNzRqb3UwMXZhMnFvZzExYXZmYmxyIn0.X80PFeerveeNlOlkLrGWsw"></div>
          </div>
      </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
  </div>
         <div class="card-body">
         <h5>A Quick Introduction to <%= @user.name %> </h5>
            <p class="card-text">
               <%= @user.bio %>
            </p>
         </div>
         <div class="button-container">
         <%= link_to "Talk To Me", { :controller => "chatrooms", :action => "start_chat", user: @user}, class: "btn primary-button btn-sm" %>
         </div>
</div>


<div class ="upperbar">
   <div class="reviews-title">
      <span>Reviews</span><%= link_to "Add A Review", new_user_review_path(@user) %>
   </div>
   <div class="reviews">
      <% @reviews.each do |review| %>
         <div class="review-card">
            <blockquote class="blockquote mb-0">
              <div class="stars">
               <p><%= '⭐️' * review.rating %></p>
               <p><%= review.content %></p>
               <span><%= review.reviewer.username %></span>
            </blockquote>
         </div>
      <% end %>
   </div>
</div>